package com.viridian.service.statement.persistence.auto;

import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.viridian.service.statement.persistence.Users;

/**
 * Class _AuthAdapter was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AuthAdapter extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> ADAPTER_CONFIG = Property.create("adapterConfig", String.class);
    public static final Property<LocalDateTime> CREATED_DATE = Property.create("createdDate", LocalDateTime.class);
    public static final Property<LocalDateTime> DISABLED_DATE = Property.create("disabledDate", LocalDateTime.class);
    public static final Property<Boolean> ENABLED = Property.create("enabled", Boolean.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> PK = Property.create("pk", String.class);
    public static final Property<List<Users>> X_CREATED_USER = Property.create("xCREATED_USER", List.class);
    public static final Property<Users> X_DISABLED_USER = Property.create("xDISABLED_USER", Users.class);

    public void setAdapterConfig(String adapterConfig) {
        writeProperty("adapterConfig", adapterConfig);
    }
    public String getAdapterConfig() {
        return (String)readProperty("adapterConfig");
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        writeProperty("createdDate", createdDate);
    }
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime)readProperty("createdDate");
    }

    public void setDisabledDate(LocalDateTime disabledDate) {
        writeProperty("disabledDate", disabledDate);
    }
    public LocalDateTime getDisabledDate() {
        return (LocalDateTime)readProperty("disabledDate");
    }

    public void setEnabled(boolean enabled) {
        writeProperty("enabled", enabled);
    }
	public boolean isEnabled() {
        Boolean value = (Boolean)readProperty("enabled");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPk(String pk) {
        writeProperty("pk", pk);
    }
    public String getPk() {
        return (String)readProperty("pk");
    }

    public void addToXCREATED_USER(Users obj) {
        addToManyTarget("xCREATED_USER", obj, true);
    }
    public void removeFromXCREATED_USER(Users obj) {
        removeToManyTarget("xCREATED_USER", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Users> getXCREATED_USER() {
        return (List<Users>)readProperty("xCREATED_USER");
    }


    public void setXDISABLED_USER(Users xDISABLED_USER) {
        setToOneTarget("xDISABLED_USER", xDISABLED_USER, true);
    }

    public Users getXDISABLED_USER() {
        return (Users)readProperty("xDISABLED_USER");
    }


}
