package com.viridian.service.statement.persistence.auto;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.viridian.service.statement.persistence.SendAdapter;
import com.viridian.service.statement.persistence.StatementDetail;
import com.viridian.service.statement.persistence.Users;

/**
 * Class _StatementHeader was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _StatementHeader extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> ACCOUNT = Property.create("account", String.class);
    public static final Property<Boolean> COMPLETED = Property.create("completed", Boolean.class);
    public static final Property<LocalDateTime> CREATED_DATE = Property.create("createdDate", LocalDateTime.class);
    public static final Property<LocalDateTime> DISABLED_DATE = Property.create("disabledDate", LocalDateTime.class);
    public static final Property<Boolean> ENABLED = Property.create("enabled", Boolean.class);
    public static final Property<BigDecimal> END_BALANCE = Property.create("endBalance", BigDecimal.class);
    public static final Property<LocalDateTime> GENERATED_DATE = Property.create("generatedDate", LocalDateTime.class);
    public static final Property<Boolean> RESEND = Property.create("resend", Boolean.class);
    public static final Property<Integer> RESEND_ATTEMPT_NUMBER = Property.create("resendAttemptNumber", Integer.class);
    public static final Property<LocalDateTime> RESEND_DATE = Property.create("resendDate", LocalDateTime.class);
    public static final Property<LocalDateTime> SEND_DATE = Property.create("sendDate", LocalDateTime.class);
    public static final Property<BigDecimal> START_BALANCE = Property.create("startBalance", BigDecimal.class);
    public static final Property<String> STATEMENT_ACCOUNT = Property.create("statementAccount", String.class);
    public static final Property<LocalDateTime> STATEMENT_DATE = Property.create("statementDate", LocalDateTime.class);
    public static final Property<Integer> TOTAL_TRANSACTIONS = Property.create("totalTransactions", Integer.class);
    public static final Property<List<StatementDetail>> STATEMENT_DETAILS = Property.create("statementDetails", List.class);
    public static final Property<Users> X_CREATED_USER = Property.create("xCREATED_USER", Users.class);
    public static final Property<Users> X_DISABLED_USER = Property.create("xDISABLED_USER", Users.class);
    public static final Property<List<Users>> X_RESEND_USER = Property.create("xRESEND_USER", List.class);
    public static final Property<SendAdapter> X_SEND_ADAPTER = Property.create("xSEND_ADAPTER", SendAdapter.class);

    public void setAccount(String account) {
        writeProperty("account", account);
    }
    public String getAccount() {
        return (String)readProperty("account");
    }

    public void setCompleted(boolean completed) {
        writeProperty("completed", completed);
    }
	public boolean isCompleted() {
        Boolean value = (Boolean)readProperty("completed");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        writeProperty("createdDate", createdDate);
    }
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime)readProperty("createdDate");
    }

    public void setDisabledDate(LocalDateTime disabledDate) {
        writeProperty("disabledDate", disabledDate);
    }
    public LocalDateTime getDisabledDate() {
        return (LocalDateTime)readProperty("disabledDate");
    }

    public void setEnabled(boolean enabled) {
        writeProperty("enabled", enabled);
    }
	public boolean isEnabled() {
        Boolean value = (Boolean)readProperty("enabled");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setEndBalance(BigDecimal endBalance) {
        writeProperty("endBalance", endBalance);
    }
    public BigDecimal getEndBalance() {
        return (BigDecimal)readProperty("endBalance");
    }

    public void setGeneratedDate(LocalDateTime generatedDate) {
        writeProperty("generatedDate", generatedDate);
    }
    public LocalDateTime getGeneratedDate() {
        return (LocalDateTime)readProperty("generatedDate");
    }

    public void setResend(boolean resend) {
        writeProperty("resend", resend);
    }
	public boolean isResend() {
        Boolean value = (Boolean)readProperty("resend");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setResendAttemptNumber(int resendAttemptNumber) {
        writeProperty("resendAttemptNumber", resendAttemptNumber);
    }
    public int getResendAttemptNumber() {
        Object value = readProperty("resendAttemptNumber");
        return (value != null) ? (Integer) value : 0;
    }

    public void setResendDate(LocalDateTime resendDate) {
        writeProperty("resendDate", resendDate);
    }
    public LocalDateTime getResendDate() {
        return (LocalDateTime)readProperty("resendDate");
    }

    public void setSendDate(LocalDateTime sendDate) {
        writeProperty("sendDate", sendDate);
    }
    public LocalDateTime getSendDate() {
        return (LocalDateTime)readProperty("sendDate");
    }

    public void setStartBalance(BigDecimal startBalance) {
        writeProperty("startBalance", startBalance);
    }
    public BigDecimal getStartBalance() {
        return (BigDecimal)readProperty("startBalance");
    }

    public void setStatementAccount(String statementAccount) {
        writeProperty("statementAccount", statementAccount);
    }
    public String getStatementAccount() {
        return (String)readProperty("statementAccount");
    }

    public void setStatementDate(LocalDateTime statementDate) {
        writeProperty("statementDate", statementDate);
    }
    public LocalDateTime getStatementDate() {
        return (LocalDateTime)readProperty("statementDate");
    }

    public void setTotalTransactions(int totalTransactions) {
        writeProperty("totalTransactions", totalTransactions);
    }
    public int getTotalTransactions() {
        Object value = readProperty("totalTransactions");
        return (value != null) ? (Integer) value : 0;
    }

    public void addToStatementDetails(StatementDetail obj) {
        addToManyTarget("statementDetails", obj, true);
    }
    public void removeFromStatementDetails(StatementDetail obj) {
        removeToManyTarget("statementDetails", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<StatementDetail> getStatementDetails() {
        return (List<StatementDetail>)readProperty("statementDetails");
    }


    public void setXCREATED_USER(Users xCREATED_USER) {
        setToOneTarget("xCREATED_USER", xCREATED_USER, true);
    }

    public Users getXCREATED_USER() {
        return (Users)readProperty("xCREATED_USER");
    }


    public void setXDISABLED_USER(Users xDISABLED_USER) {
        setToOneTarget("xDISABLED_USER", xDISABLED_USER, true);
    }

    public Users getXDISABLED_USER() {
        return (Users)readProperty("xDISABLED_USER");
    }


    public void addToXRESEND_USER(Users obj) {
        addToManyTarget("xRESEND_USER", obj, true);
    }
    public void removeFromXRESEND_USER(Users obj) {
        removeToManyTarget("xRESEND_USER", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Users> getXRESEND_USER() {
        return (List<Users>)readProperty("xRESEND_USER");
    }


    public void setXSEND_ADAPTER(SendAdapter xSEND_ADAPTER) {
        setToOneTarget("xSEND_ADAPTER", xSEND_ADAPTER, true);
    }

    public SendAdapter getXSEND_ADAPTER() {
        return (SendAdapter)readProperty("xSEND_ADAPTER");
    }


}
