package com.viridian.service.statement.persistence.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.viridian.service.statement.persistence.StatementHeader;

/**
 * Class _StatementDetail was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _StatementDetail extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<BigDecimal> AMOUNT = Property.create("amount", BigDecimal.class);
    public static final Property<String> DEBIT_CREDIT = Property.create("debitCredit", String.class);
    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<BigDecimal> START_BALANCE = Property.create("startBalance", BigDecimal.class);
    public static final Property<String> STATEMENT_ACCOUNT = Property.create("statementAccount", String.class);
    public static final Property<String> TRANSACTION_CODE = Property.create("transactionCode", String.class);
    public static final Property<String> TRANSACTION_ID = Property.create("transactionId", String.class);
    public static final Property<String> TRANSACTION_TYPE = Property.create("transactionType", String.class);
    public static final Property<StatementHeader> X_HEADER_ID = Property.create("xHEADER_ID", StatementHeader.class);

    public void setAmount(BigDecimal amount) {
        writeProperty("amount", amount);
    }
    public BigDecimal getAmount() {
        return (BigDecimal)readProperty("amount");
    }

    public void setDebitCredit(String debitCredit) {
        writeProperty("debitCredit", debitCredit);
    }
    public String getDebitCredit() {
        return (String)readProperty("debitCredit");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setStartBalance(BigDecimal startBalance) {
        writeProperty("startBalance", startBalance);
    }
    public BigDecimal getStartBalance() {
        return (BigDecimal)readProperty("startBalance");
    }

    public void setStatementAccount(String statementAccount) {
        writeProperty("statementAccount", statementAccount);
    }
    public String getStatementAccount() {
        return (String)readProperty("statementAccount");
    }

    public void setTransactionCode(String transactionCode) {
        writeProperty("transactionCode", transactionCode);
    }
    public String getTransactionCode() {
        return (String)readProperty("transactionCode");
    }

    public void setTransactionId(String transactionId) {
        writeProperty("transactionId", transactionId);
    }
    public String getTransactionId() {
        return (String)readProperty("transactionId");
    }

    public void setTransactionType(String transactionType) {
        writeProperty("transactionType", transactionType);
    }
    public String getTransactionType() {
        return (String)readProperty("transactionType");
    }

    public void setXHEADER_ID(StatementHeader xHEADER_ID) {
        setToOneTarget("xHEADER_ID", xHEADER_ID, true);
    }

    public StatementHeader getXHEADER_ID() {
        return (StatementHeader)readProperty("xHEADER_ID");
    }


}
