package cc.viridian.service.statement.persistence.auto;

import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import cc.viridian.service.statement.persistence.CustomerAccount;
import cc.viridian.service.statement.persistence.Users;

/**
 * Class _Customer was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Customer extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> ADDRESS = Property.create("address", String.class);
    public static final Property<String> CODE = Property.create("code", String.class);
    public static final Property<LocalDateTime> CREATED_DATE = Property.create("createdDate", LocalDateTime.class);
    public static final Property<LocalDateTime> DISABLED_DATE = Property.create("disabledDate", LocalDateTime.class);
    public static final Property<Boolean> ENABLED = Property.create("enabled", Boolean.class);
    public static final Property<String> LASTNAME = Property.create("lastname", String.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> PHONE = Property.create("phone", String.class);
    public static final Property<String> PK = Property.create("pk", String.class);
    public static final Property<String> TYPE = Property.create("type", String.class);
    public static final Property<Users> X_CREATED_USER = Property.create("xCREATED_USER", Users.class);
    public static final Property<List<CustomerAccount>> X_CUSTOMER = Property.create("xCUSTOMER", List.class);
    public static final Property<Users> X_DISABLED_USER = Property.create("xDISABLED_USER", Users.class);

    public void setAddress(String address) {
        writeProperty("address", address);
    }
    public String getAddress() {
        return (String)readProperty("address");
    }

    public void setCode(String code) {
        writeProperty("code", code);
    }
    public String getCode() {
        return (String)readProperty("code");
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        writeProperty("createdDate", createdDate);
    }
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime)readProperty("createdDate");
    }

    public void setDisabledDate(LocalDateTime disabledDate) {
        writeProperty("disabledDate", disabledDate);
    }
    public LocalDateTime getDisabledDate() {
        return (LocalDateTime)readProperty("disabledDate");
    }

    public void setEnabled(boolean enabled) {
        writeProperty("enabled", enabled);
    }
	public boolean isEnabled() {
        Boolean value = (Boolean)readProperty("enabled");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setLastname(String lastname) {
        writeProperty("lastname", lastname);
    }
    public String getLastname() {
        return (String)readProperty("lastname");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPhone(String phone) {
        writeProperty("phone", phone);
    }
    public String getPhone() {
        return (String)readProperty("phone");
    }

    public void setPk(String pk) {
        writeProperty("pk", pk);
    }
    public String getPk() {
        return (String)readProperty("pk");
    }

    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }

    public void setXCREATED_USER(Users xCREATED_USER) {
        setToOneTarget("xCREATED_USER", xCREATED_USER, true);
    }

    public Users getXCREATED_USER() {
        return (Users)readProperty("xCREATED_USER");
    }


    public void addToXCUSTOMER(CustomerAccount obj) {
        addToManyTarget("xCUSTOMER", obj, true);
    }
    public void removeFromXCUSTOMER(CustomerAccount obj) {
        removeToManyTarget("xCUSTOMER", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CustomerAccount> getXCUSTOMER() {
        return (List<CustomerAccount>)readProperty("xCUSTOMER");
    }


    public void setXDISABLED_USER(Users xDISABLED_USER) {
        setToOneTarget("xDISABLED_USER", xDISABLED_USER, true);
    }

    public Users getXDISABLED_USER() {
        return (Users)readProperty("xDISABLED_USER");
    }


}
