package cc.viridian.service.statement.persistence.auto;

import java.time.LocalDateTime;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Format was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Format extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> ATTRIBUTES = Property.create("attributes", String.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<LocalDateTime> TIME_CREATE = Property.create("timeCreate", LocalDateTime.class);
    public static final Property<LocalDateTime> TIME_MODIFY = Property.create("timeModify", LocalDateTime.class);
    public static final Property<String> USR_CREATE = Property.create("usrCreate", String.class);
    public static final Property<String> USR_MODIFY = Property.create("usrModify", String.class);

    public void setAttributes(String attributes) {
        writeProperty("attributes", attributes);
    }
    public String getAttributes() {
        return (String)readProperty("attributes");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setTimeCreate(LocalDateTime timeCreate) {
        writeProperty("timeCreate", timeCreate);
    }
    public LocalDateTime getTimeCreate() {
        return (LocalDateTime)readProperty("timeCreate");
    }

    public void setTimeModify(LocalDateTime timeModify) {
        writeProperty("timeModify", timeModify);
    }
    public LocalDateTime getTimeModify() {
        return (LocalDateTime)readProperty("timeModify");
    }

    public void setUsrCreate(String usrCreate) {
        writeProperty("usrCreate", usrCreate);
    }
    public String getUsrCreate() {
        return (String)readProperty("usrCreate");
    }

    public void setUsrModify(String usrModify) {
        writeProperty("usrModify", usrModify);
    }
    public String getUsrModify() {
        return (String)readProperty("usrModify");
    }

}
