package cc.viridian.service.statement.persistence.auto;

import cc.viridian.service.statement.persistence.Permission;
import cc.viridian.service.statement.persistence.Role;
import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _RolePermission was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RolePermission extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String PERMISSION_ID_PK_COLUMN = "PERMISSION_ID";
    public static final String ROLE_ID_PK_COLUMN = "ROLE_ID";

    public static final Property<Permission> X_PERMISSION = Property.create("xPERMISSION", Permission.class);
    public static final Property<Role> X_ROLE = Property.create("xROLE", Role.class);

    public void setXPERMISSION(Permission xPERMISSION) {
        setToOneTarget("xPERMISSION", xPERMISSION, true);
    }

    public Permission getXPERMISSION() {
        return (Permission)readProperty("xPERMISSION");
    }


    public void setXROLE(Role xROLE) {
        setToOneTarget("xROLE", xROLE, true);
    }

    public Role getXROLE() {
        return (Role)readProperty("xROLE");
    }


}
