package cc.viridian.service.statement.persistence.auto;

import java.util.List;

import cc.viridian.service.statement.persistence.RolePermission;
import cc.viridian.service.statement.persistence.Users;
import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Role was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Role extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<RolePermission>> X_ROLE = Property.create("xROLE", List.class);
    public static final Property<List<Users>> X_USER = Property.create("xUSER", List.class);

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToXROLE(RolePermission obj) {
        addToManyTarget("xROLE", obj, true);
    }
    public void removeFromXROLE(RolePermission obj) {
        removeToManyTarget("xROLE", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RolePermission> getXROLE() {
        return (List<RolePermission>)readProperty("xROLE");
    }


    public void addToXUSER(Users obj) {
        addToManyTarget("xUSER", obj, true);
    }
    public void removeFromXUSER(Users obj) {
        removeToManyTarget("xUSER", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Users> getXUSER() {
        return (List<Users>)readProperty("xUSER");
    }


}
