package cc.viridian.service.statement.persistence.auto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _StatementDetail was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _StatementDetail extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> ACCOUNT_CODE = Property.create("accountCode", String.class);
    public static final Property<String> ACCOUNT_CURRENCY = Property.create("accountCurrency", String.class);
    public static final Property<String> ACCOUNT_TYPE = Property.create("accountType", String.class);
    public static final Property<BigDecimal> AMOUNT = Property.create("amount", BigDecimal.class);
    public static final Property<String> ANNOTATION = Property.create("annotation", String.class);
    public static final Property<BigDecimal> BALANCE = Property.create("balance", BigDecimal.class);
    public static final Property<String> BRANCH_CHANNEL = Property.create("branchChannel", String.class);
    public static final Property<String> DATE = Property.create("date", String.class);
    public static final Property<String> DEBIT_CREDIT = Property.create("debitCredit", String.class);
    public static final Property<LocalDateTime> LOCAL_DATE_TIME = Property.create("localDateTime", LocalDateTime.class);
    public static final Property<String> REFERENCE_NUMBER = Property.create("referenceNumber", String.class);
    public static final Property<String> SECONDARY_INFO = Property.create("secondaryInfo", String.class);
    public static final Property<String> TRANSACTION_CODE = Property.create("transactionCode", String.class);
    public static final Property<String> TRANSACTION_DESC = Property.create("transactionDesc", String.class);
    public static final Property<String> TRN_ID = Property.create("trnId", String.class);

    public void setAccountCode(String accountCode) {
        writeProperty("accountCode", accountCode);
    }
    public String getAccountCode() {
        return (String)readProperty("accountCode");
    }

    public void setAccountCurrency(String accountCurrency) {
        writeProperty("accountCurrency", accountCurrency);
    }
    public String getAccountCurrency() {
        return (String)readProperty("accountCurrency");
    }

    public void setAccountType(String accountType) {
        writeProperty("accountType", accountType);
    }
    public String getAccountType() {
        return (String)readProperty("accountType");
    }

    public void setAmount(BigDecimal amount) {
        writeProperty("amount", amount);
    }
    public BigDecimal getAmount() {
        return (BigDecimal)readProperty("amount");
    }

    public void setAnnotation(String annotation) {
        writeProperty("annotation", annotation);
    }
    public String getAnnotation() {
        return (String)readProperty("annotation");
    }

    public void setBalance(BigDecimal balance) {
        writeProperty("balance", balance);
    }
    public BigDecimal getBalance() {
        return (BigDecimal)readProperty("balance");
    }

    public void setBranchChannel(String branchChannel) {
        writeProperty("branchChannel", branchChannel);
    }
    public String getBranchChannel() {
        return (String)readProperty("branchChannel");
    }

    public void setDate(String date) {
        writeProperty("date", date);
    }
    public String getDate() {
        return (String)readProperty("date");
    }

    public void setDebitCredit(String debitCredit) {
        writeProperty("debitCredit", debitCredit);
    }
    public String getDebitCredit() {
        return (String)readProperty("debitCredit");
    }

    public void setLocalDateTime(LocalDateTime localDateTime) {
        writeProperty("localDateTime", localDateTime);
    }
    public LocalDateTime getLocalDateTime() {
        return (LocalDateTime)readProperty("localDateTime");
    }

    public void setReferenceNumber(String referenceNumber) {
        writeProperty("referenceNumber", referenceNumber);
    }
    public String getReferenceNumber() {
        return (String)readProperty("referenceNumber");
    }

    public void setSecondaryInfo(String secondaryInfo) {
        writeProperty("secondaryInfo", secondaryInfo);
    }
    public String getSecondaryInfo() {
        return (String)readProperty("secondaryInfo");
    }

    public void setTransactionCode(String transactionCode) {
        writeProperty("transactionCode", transactionCode);
    }
    public String getTransactionCode() {
        return (String)readProperty("transactionCode");
    }

    public void setTransactionDesc(String transactionDesc) {
        writeProperty("transactionDesc", transactionDesc);
    }
    public String getTransactionDesc() {
        return (String)readProperty("transactionDesc");
    }

    public void setTrnId(String trnId) {
        writeProperty("trnId", trnId);
    }
    public String getTrnId() {
        return (String)readProperty("trnId");
    }

}
